#!/usr/bin/env bash
# One-shot prep for ios/SpacySmoke (macOS): generate ldflags + Dist.xcconfig + Xcode project.
# Prerequisites: Xcode, XcodeGen (`brew install xcodegen`), rsync, realpath.
#
# Usage:
#   export DIST_PATH="/path/to/extracted/dist"
#   ./scripts/ios/bootstrap_spacy_smoke_xcode.sh [DIST_PATH]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DIST_PATH="${1:-${DIST_PATH:-}}"

if [[ -z "$DIST_PATH" || ! -d "$DIST_PATH/root/python3" ]]; then
  echo "Set DIST_PATH to kivy-ios dist root (must contain root/python3/)." >&2
  echo "Example: run scripts/download_latest_dist.sh then:" >&2
  echo "  export DIST_PATH=\"\$(realpath .artifacts/latest-dist/extracted/dist)\"" >&2
  exit 1
fi

GEN="$ROOT/ios/SpacySmoke/Generated"
mkdir -p "$GEN"

REAL_DIST="$(cd "$DIST_PATH" && pwd)"
echo "DIST_PATH=$REAL_DIST"

"$ROOT/scripts/ios/gen_ldflags_xcconfig.sh" "$REAL_DIST" "$GEN/ldflags.xcconfig"

cat >"$GEN/Dist.xcconfig" <<EOF
// Regenerated by bootstrap_spacy_smoke_xcode.sh — safe to gitignore

DIST_PATH = $REAL_DIST

#include "ldflags.xcconfig"
EOF

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Install XcodeGen: brew install xcodegen" >&2
  exit 1
fi

(cd "$ROOT/ios/SpacySmoke" && xcodegen generate)

echo "OK: $ROOT/ios/SpacySmoke/SpacySmoke.xcodeproj"
echo "Open with: open ios/SpacySmoke/SpacySmoke.xcodeproj"
