#!/usr/bin/env bash
# Emit an xcconfig fragment with OTHER_LDFLAGS force-loading every static
# library under dist/lib/iphoneos. Run on macOS before `xcodegen generate`.
#
# Usage: gen_ldflags_xcconfig.sh <path-to-dist-root> <output-xcconfig>
#
# If linking fails (order / duplicates), use `toolchain update` from kivy-ios
# against the same tree that produced dist/state.db, or trim/reorder libs.

set -euo pipefail

DIST_ROOT="${1:?dist root (contains lib/iphoneos)}"
OUT="${2:?output xcconfig path}"

LIBDIR="${DIST_ROOT}/lib/iphoneos"
if [[ ! -d "$LIBDIR" ]]; then
  echo "No libdir $LIBDIR" >&2
  exit 1
fi

{
  echo "// Generated by kivy-ios-recipes/scripts/ios/gen_ldflags_xcconfig.sh"
  echo -n "OTHER_LDFLAGS = \$(inherited) "
  while IFS= read -r f; do
    printf -- '-force_load \"%s\" ' "$f"
  done < <(find "$LIBDIR" -name '*.a' | sort)
  echo ""
} >"$OUT"

n="$(grep -o 'force_load' "$OUT" | wc -l | tr -d ' ')"
echo "Wrote $OUT ($n static libs)"
